export const ANIMAL_LIST = [
  { id: 1, name: 'Aligator', type: '' },
  { id: 2, name: 'Alpaka', type: '' },
  { id: 3, name: 'Angsa', type: '' },
  { id: 4, name: 'Anjing', type: '' },
  { id: 5, name: 'Anoa', type: '' },
  { id: 6, name: 'Antelop', type: '' },
  { id: 7, name: 'Arwana', type: 'Ikan' },
  { id: 8, name: 'Ayam', type: '' },

  { id: 9, name: 'Babi', type: '' },
  { id: 10, name: 'Badak', type: '' },
  { id: 11, name: 'Bandeng', type: 'Ikan' },
  { id: 12, name: 'Bangau', type: 'Burung' },
  { id: 13, name: 'Banteng', type: '' },
  { id: 14, name: 'Bawal', type: 'Ikan' },
  { id: 15, name: 'Bebek', type: '' },
  { id: 16, name: 'Belalang', type: '' },
  { id: 17, name: 'Belut', type: '' },
  { id: 18, name: 'Beo', type: 'Burung' },
  { id: 19, name: 'Beruang', type: '' },
  { id: 20, name: 'Bison', type: '' },
  { id: 21, name: 'Buaya', type: '' },
  { id: 22, name: 'Bunglon', type: '' },
  { id: 23, name: 'Hantu', type: 'Burung' },

  { id: 24, name: 'Cacing', type: '' },
  { id: 25, name: 'Camar', type: 'Burung' },
  { id: 26, name: 'Capung', type: '' },
  { id: 28, name: 'Cendrawasih', type: 'Burung' },
  { id: 29, name: 'Cicak', type: '' },
  { id: 30, name: 'Cupang', type: 'Ikan' },
  { id: 31, name: 'Cumi-cumi', type: '' },

  { id: 32, name: 'Dara', type: 'Burung' },
  { id: 33, name: 'Dingo', type: '' },
  { id: 34, name: 'Domba', type: '' },
  { id: 35, name: 'Dugong', type: '' },

  { id: 36, name: 'Elang', type: 'Burung' },
  { id: 37, name: 'Emprit', type: 'Burung' },
  { id: 38, name: 'Entog', type: '' },

  { id: 39, name: 'Flamingo', type: '' },

  { id: 41, name: 'Gabus', type: 'Ikan' },
  { id: 42, name: 'Gagak', type: 'Burung' },
  { id: 43, name: 'Gajah', type: '' },
  { id: 44, name: 'Gelatik', type: 'Burung' },
  { id: 45, name: 'Gorila', type: '' },
  { id: 46, name: 'Gurita', type: '' },

  { id: 47, name: 'Hamster', type: '' },
  { id: 48, name: 'Harimau', type: '' },
  { id: 49, name: 'Hering', type: 'Burung' },
  { id: 50, name: 'Hiu', type: 'Ikan' },

  { id: 51, name: 'Iguana', type: '' },
  { id: 52, name: 'Itik', type: '' },

  { id: 53, name: 'Jaguar', type: '' },
  { id: 54, name: 'Jalak', type: 'Burung' },
  { id: 55, name: 'Jangkrik', type: '' },
  { id: 56, name: 'Japuh', type: 'Ikan' },
  { id: 57, name: 'Jelawat', type: 'Ikan' },
  { id: 58, name: 'Jerapah', type: '' },

  { id: 59, name: 'Kadal', type: '' },
  { id: 60, name: 'Kakatua', type: 'Burung' },
  { id: 61, name: 'Kakap', type: 'Ikan' },
  { id: 62, name: 'Kambing', type: '' },
  { id: 63, name: 'Kancil', type: '' },
  { id: 64, name: 'Katak', type: '' },
  { id: 65, name: 'Kelelawar', type: '' },
  { id: 66, name: 'Kelinci', type: '' },
  { id: 67, name: 'Kenari', type: 'Burung' },
  { id: 68, name: 'Kepiting', type: '' },
  { id: 69, name: 'Kijang', type: '' },
  { id: 70, name: 'Koala', type: '' },
  { id: 72, name: 'Kerapu', type: 'Ikan' },
  { id: 73, name: 'Kucing', type: '' },
  { id: 74, name: 'Kuda', type: '' },
  { id: 75, name: 'Kukang', type: '' },
  { id: 76, name: 'Kumbang', type: '' },
  { id: 77, name: 'Kuntul', type: 'Burung' },
  { id: 78, name: 'Kupu-kupu', type: '' },
  { id: 79, name: 'Kura-kura', type: '' },

  { id: 80, name: 'Laba-laba', type: '' },
  { id: 81, name: 'Lalat', type: '' },
  { id: 82, name: 'Landak', type: '' },
  { id: 83, name: 'Lebah', type: '' },
  { id: 84, name: 'Lele', type: 'Ikan' },
  { id: 85, name: 'Lipan', type: '' },
  { id: 86, name: 'Lumba-lumba', type: '' },

  { id: 87, name: 'Macan Tutul', type: '' },
  { id: 88, name: 'Marmot', type: '' },
  { id: 89, name: 'Mas', type: 'Ikan' },
  { id: 90, name: 'Merak', type: 'Burung' },
  { id: 91, name: 'Merpati', type: 'Burung' },
  { id: 92, name: 'Monyet', type: '' },
  { id: 93, name: 'Mujair', type: 'Ikan' },
  { id: 94, name: 'Musang', type: '' },

  { id: 95, name: 'Ngengat', type: '' },
  { id: 96, name: 'Nila', type: 'Ikan' },
  { id: 97, name: 'Nuri', type: 'Burung' },
  { id: 98, name: 'Nyamuk', type: '' },

  { id: 99, name: 'Orangutan', type: '' },

  { id: 100, name: 'Panda', type: '' },
  { id: 102, name: 'Patin', type: 'Ikan' },
  { id: 103, name: 'Paus', type: '' },
  { id: 104, name: 'Pelikan', type: 'Burung' },
  { id: 105, name: 'Penguin', type: '' },
  { id: 106, name: 'Penyu', type: '' },
  { id: 107, name: 'Perkutut', type: 'Burung' },

  { id: 108, name: 'Quokka', type: '' },

  { id: 109, name: 'Rajawali', type: 'Burung' },
  { id: 110, name: 'Rakun', type: '' },
  { id: 111, name: 'Rubah', type: '' },
  { id: 112, name: 'Rusa', type: '' },

  { id: 113, name: 'Salmon', type: 'Ikan' },
  { id: 114, name: 'Sapi', type: '' },
  { id: 115, name: 'Semut', type: '' },
  { id: 116, name: 'Serigala', type: '' },
  { id: 117, name: 'Sidat', type: '' },
  { id: 118, name: 'Singa', type: '' },
  { id: 119, name: 'Siput', type: '' },

  { id: 120, name: 'Tawon', type: '' },
  { id: 121, name: 'Tekukur', type: 'Burung' },
  { id: 122, name: 'Tikus', type: '' },
  { id: 124, name: 'Tongkol', type: 'Ikan' },
  { id: 125, name: 'Trenggiling', type: '' },
  { id: 126, name: 'Tupai', type: '' },

  { id: 127, name: 'Ubur-ubur', type: '' },
  { id: 128, name: 'Udang', type: '' },
  { id: 129, name: 'Ulat', type: '' },
  { id: 130, name: 'Ular', type: '' },
  { id: 131, name: 'Unta', type: '' },

  { id: 133, name: 'Walrus', type: '' },
  { id: 134, name: 'Walet', type: 'Burung' },

  { id: 136, name: 'Yak', type: '' },

  { id: 137, name: 'Zebra', type: '' },

  { id: 138, name: 'Rayap', type: '' },
  { id: 139, name: 'Kunang-kunang', type: '' },
  { id: 140, name: 'Laron', type: '' },
  { id: 141, name: 'Undur-undur', type: '' },
  { id: 142, name: 'Lemur', type: '' },
  { id: 143, name: 'Keledai', type: '' },
  { id: 144, name: 'Tonggeret', type: '' },
  { id: 145, name: 'Kolibri', type: 'Burung' },
  { id: 146, name: 'Kepik', type: '' },
  { id: 147, name: 'Kerang', type: '' },
];
